package com.fantasyweapons.sound;

import com.fantasyweapons.FantasyWeapons;
import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Every custom sound event of the mod. Each maps (in assets/fantasyweapons/sounds.json) to an .ogg in
 * assets/fantasyweapons/sounds/. The shipped files are synthesised placeholders generated by tools/gen_sounds.py;
 * replacing a sound only requires dropping a new .ogg with the same name.
 */
public final class ModSounds {
    public static final DeferredRegister<SoundEvent> REGISTER = DeferredRegister.create(Registries.SOUND_EVENT, FantasyWeapons.MOD_ID);

    // weapon
    public static final DeferredHolder<SoundEvent, SoundEvent> WEAPON_SWING = reg("weapon.swing");
    public static final DeferredHolder<SoundEvent, SoundEvent> WEAPON_SWING_HEAVY = reg("weapon.swing_heavy");
    public static final DeferredHolder<SoundEvent, SoundEvent> WEAPON_HIT = reg("weapon.hit");
    public static final DeferredHolder<SoundEvent, SoundEvent> HEAVY_IMPACT = reg("weapon.heavy_impact");
    // ability lifecycle
    public static final DeferredHolder<SoundEvent, SoundEvent> CHARGE_START = reg("ability.charge_start");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHARGE_LOOP = reg("ability.charge_loop");
    public static final DeferredHolder<SoundEvent, SoundEvent> FULL_CHARGE = reg("ability.full_charge");
    public static final DeferredHolder<SoundEvent, SoundEvent> ABILITY_ACTIVATE = reg("ability.activate");
    public static final DeferredHolder<SoundEvent, SoundEvent> ABILITY_IMPACT = reg("ability.impact");
    public static final DeferredHolder<SoundEvent, SoundEvent> ABILITY_FIZZLE = reg("ability.fizzle");
    public static final DeferredHolder<SoundEvent, SoundEvent> ABILITY_DENIED = reg("ability.denied");
    // progression
    public static final DeferredHolder<SoundEvent, SoundEvent> LEVEL_UP = reg("progression.level_up");
    public static final DeferredHolder<SoundEvent, SoundEvent> ABILITY_UNLOCK = reg("progression.ability_unlock");
    public static final DeferredHolder<SoundEvent, SoundEvent> UPGRADE = reg("progression.upgrade");
    public static final DeferredHolder<SoundEvent, SoundEvent> EXP_GAIN = reg("progression.exp");
    public static final DeferredHolder<SoundEvent, SoundEvent> UI_CLICK = reg("ui.click");
    public static final DeferredHolder<SoundEvent, SoundEvent> UI_HOVER = reg("ui.hover");
    // forms
    public static final DeferredHolder<SoundEvent, SoundEvent> MODE_TRANSFORM = reg("form.mode_transform");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAIN_TRANSFORM = reg("form.chain_transform");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAIN_RETRACT = reg("form.chain_retract");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAIN_ATTACK = reg("form.chain_attack");
    // elements / ability types
    public static final DeferredHolder<SoundEvent, SoundEvent> VOID_SLASH = reg("void.slash");
    public static final DeferredHolder<SoundEvent, SoundEvent> TELEPORT = reg("void.teleport");
    public static final DeferredHolder<SoundEvent, SoundEvent> RIFT_OPEN = reg("void.rift_open");
    public static final DeferredHolder<SoundEvent, SoundEvent> RIFT_CLOSE = reg("void.rift_close");
    public static final DeferredHolder<SoundEvent, SoundEvent> VOID_EXECUTION = reg("void.execution");
    public static final DeferredHolder<SoundEvent, SoundEvent> VOID_DIMENSION = reg("void.dimension");
    public static final DeferredHolder<SoundEvent, SoundEvent> EXPLOSION = reg("element.explosion");
    public static final DeferredHolder<SoundEvent, SoundEvent> SOLAR_BURST = reg("element.solar_burst");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIGHTNING = reg("element.lightning");
    public static final DeferredHolder<SoundEvent, SoundEvent> ICE_BURST = reg("element.ice_burst");
    public static final DeferredHolder<SoundEvent, SoundEvent> SOUL_PROJECTILE = reg("element.soul_projectile");
    public static final DeferredHolder<SoundEvent, SoundEvent> SCYTHE_THROW = reg("element.scythe_throw");
    public static final DeferredHolder<SoundEvent, SoundEvent> SCYTHE_RETURN = reg("element.scythe_return");
    public static final DeferredHolder<SoundEvent, SoundEvent> NATURE_GROWTH = reg("element.nature_growth");
    public static final DeferredHolder<SoundEvent, SoundEvent> METEOR_IMPACT = reg("element.meteor_impact");
    public static final DeferredHolder<SoundEvent, SoundEvent> GRAVITY = reg("element.gravity");
    public static final DeferredHolder<SoundEvent, SoundEvent> EARTH_IMPACT = reg("element.earth_impact");
    public static final DeferredHolder<SoundEvent, SoundEvent> ENERGY_FIRE = reg("element.energy_fire");
    public static final DeferredHolder<SoundEvent, SoundEvent> BLOOD_RAGE = reg("element.blood_rage");
    public static final DeferredHolder<SoundEvent, SoundEvent> FIRE_WHOOSH = reg("element.fire_whoosh");

    private ModSounds() {
    }

    private static DeferredHolder<SoundEvent, SoundEvent> reg(String name) {
        return REGISTER.register(name, () -> SoundEvent.createVariableRangeEvent(FantasyWeapons.id(name)));
    }
}
