org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.255
neo_version_range=[21.1.200,)
loader_version_range=[4,)

## Dependencies
geckolib_version=4.9.3

## Mod
mod_id=fantasyweapons
mod_name=Fantasy Weapons
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.fantasyweapons
mod_authors=kristian652andonov
mod_description=A progression-based fantasy RPG weapon system: 13 legendary weapons with their own levels, EXP, charged abilities, custom VFX and a custom HUD.
