package com.fantasyweapons.client.render;

import com.fantasyweapons.FantasyWeapons;
import com.fantasyweapons.weapon.FantasyWeaponItem;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.model.GeoModel;

/**
 * Points GeckoLib at the artist-supplied files. Supplementary animations (generated by tools/gen_extra_animations.py,
 * e.g. Infernochain's {@code chain_idle}) live in {@code <weapon>_extra.animation.json} and are found via the fallback
 * list, so the original animation files are never modified.
 */
public class WeaponGeoModel extends GeoModel<FantasyWeaponItem> {
    @Override
    public ResourceLocation getModelResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("geo/item/" + item.definition().geoName() + ".geo.json");
    }

    @Override
    public ResourceLocation getTextureResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("textures/item/" + item.definition().geoName() + ".png");
    }

    @Override
    public ResourceLocation getAnimationResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("animations/item/" + item.definition().geoName() + ".animation.json");
    }

    @Override
    public ResourceLocation[] getAnimationResourceFallbacks(FantasyWeaponItem item) {
        return new ResourceLocation[]{FantasyWeapons.id("animations/item/" + item.definition().geoName() + "_extra.animation.json")};
    }
}
