package com.fantasyweapons.client.render;

import com.fantasyweapons.FantasyWeapons;
import com.fantasyweapons.weapon.FantasyWeaponItem;
import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix3f;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import software.bernie.geckolib.animation.AnimationState;
import software.bernie.geckolib.animation.state.BoneSnapshot;
import software.bernie.geckolib.cache.object.GeoBone;
import software.bernie.geckolib.model.GeoModel;
import software.bernie.geckolib.util.RenderUtil;

import java.util.HashMap;
import java.util.Map;

/**
 * Points GeckoLib at the artist-supplied files. Supplementary animations (generated by tools/gen_extra_animations.py,
 * e.g. Infernochain's {@code chain_idle}) live in {@code <weapon>_extra.animation.json} and are found via the fallback
 * list, so the original animation files are never modified.
 */
public class WeaponGeoModel extends GeoModel<FantasyWeaponItem> {
    @Override
    public ResourceLocation getModelResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("geo/item/" + item.definition().geoName() + ".geo.json");
    }

    @Override
    public ResourceLocation getTextureResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("textures/item/" + item.definition().geoName() + ".png");
    }

    @Override
    public ResourceLocation getAnimationResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("animations/item/" + item.definition().geoName() + ".animation.json");
    }

    @Override
    public ResourceLocation[] getAnimationResourceFallbacks(FantasyWeaponItem item) {
        return new ResourceLocation[]{FantasyWeapons.id("animations/item/" + item.definition().geoName() + "_extra.animation.json")};
    }

    /** DEVELOPMENT ONLY: logs the rendered rotation of this bone every frame (to check blends don't unwind). */
    public static String debugBone;

    /**
     * Several of the artist's animations end with parts turned through whole revolutions (Stormbreaker's Tempest
     * Spin finishes its head at 720 degrees), or in a second form of the rest orientation such as (-180, 0, 180).
     * GeckoLib blends into the next animation from the raw angles, so the part would visibly unwind, or swing out
     * sideways about its own pivot. After every frame the remembered angles are restated in the equivalent Euler
     * angles nearest the rest pose, so every blend takes the short way round (see {@link
     * com.fantasyweapons.weapon.RigidAnimationController}, which does the same towards the next animation's start).
     */
    @Override
    public void setCustomAnimations(FantasyWeaponItem animatable, long instanceId, AnimationState<FantasyWeaponItem> state) {
        super.setCustomAnimations(animatable, instanceId, state);
        var manager = animatable.getAnimatableInstanceCache().getManagerForId(instanceId);
        if (manager == null) return;
        for (BoneSnapshot snap : manager.getBoneSnapshotCollection().values()) {
            BoneSnapshot rest = snap.getBone().getInitialSnapshot();
            // the same orientation in the Euler angles nearest the rest pose: blends back to rest (or into a bone
            // the next animation leaves alone) then take the short way round about one axis
            double[] e = com.fantasyweapons.weapon.RigidAnimationController.closestEuler(snap.getRotX() - rest.getRotX(), snap.getRotY() - rest.getRotY(),
                    snap.getRotZ() - rest.getRotZ(), 0, 0, 0);
            float x = (float) e[0] + rest.getRotX(), y = (float) e[1] + rest.getRotY(), z = (float) e[2] + rest.getRotZ();
            if (x != snap.getRotX() || y != snap.getRotY() || z != snap.getRotZ()) snap.updateRotation(x, y, z);
        }
        var main = manager.getAnimationControllers().get(FantasyWeaponItem.CONTROLLER);
        anchorGrip(animatable, main == null || main.getCurrentAnimation() == null ? "" : main.getCurrentAnimation().animation().name(),
                main instanceof com.fantasyweapons.weapon.RigidAnimationController<?> rigid ? rigid : null);
        fadeStrays(animatable, manager);
        if (debugBone != null) {
            for (String n : debugBone.split(",")) {
                getBone(n).ifPresent(b -> FantasyWeapons.LOGGER.warn("[bone] {} rot {} {} {} pos {} {} {} scale {}", n, Math.round(Math.toDegrees(b.getRotX())),
                        Math.round(Math.toDegrees(b.getRotY())), Math.round(Math.toDegrees(b.getRotZ())), b.getPosX(), b.getPosY(), b.getPosZ(), b.getScaleX()));
            }
        }
        if ("gravebite".equals(animatable.definition().geoName())) {
            // the spectral chains of the cast animations blink out of the skull and snap back; the Grave Chains
            // ability draws its own chains out of the ground, so they stay hidden in the hand
            for (GeoBone b : getAnimationProcessor().getRegisteredBones()) if (b.getName().startsWith("spectral_chain")) b.setHidden(true);
            swingLantern();
        }
    }

    private static final String[] LANTERN = {"lantern_link_0", "lantern_link_1", "lantern_link_2", "lantern_cage", "lantern_soul"};

    /**
     * Gravebite's lantern hangs from its hook by a short chain: in the hand it swings for real (see {@link
     * HangingPhysics}), hanging straight down whichever way the weapon is held, lagging behind and swinging past when
     * the weapon moves. The whole chain and lantern turn about the hook, on top of the artist's own sway.
     */
    private void swingLantern() {
        if (!HangingPhysics.active()) return;
        GeoBone hook = getBone(LANTERN[0]).orElse(null);
        GeoBone cage = getBone("lantern_cage").orElse(null);
        if (hook == null || cage == null || hook.getParent() == null) return;
        GeoBone root = hook.getParent();
        Matrix4f rootM = local(root, false);
        Vector3f pivot = local(hook, false).transformPosition(new Vector3f(hook.getPivotX() / 16f, (hook.getPivotY() + 1) / 16f, hook.getPivotZ() / 16f));
        float length = (hook.getPivotY() - cage.getPivotY() + 3) / 16f;
        Vector3f d = HangingPhysics.hang(rootM, pivot, length);
        // hanging along the haft is the rest pose; never let it swing up through the weapon
        Vector3f down = new Vector3f(0, -1, 0);
        float angle = down.angle(d);
        float max = (float) Math.toRadians(115);
        if (angle > max) d = new Vector3f(down).lerp(d, max / angle).normalize();
        org.joml.Quaternionf q = new org.joml.Quaternionf().rotationTo(down, d);
        Matrix4f turn = new Matrix4f().translation(pivot).rotate(q).translate(-pivot.x, -pivot.y, -pivot.z);
        for (String n : LANTERN) {
            GeoBone b = getBone(n).orElse(null);
            if (b != null) setLocal(b, new Matrix4f(turn).mul(local(b, false)));
        }
    }

    /** Poses a bone so its transform relative to its parent is {@code want} (rotation and translation only). */
    private static void setLocal(GeoBone bone, Matrix4f want) {
        Vector3f euler = want.get3x3(new Matrix3f()).getEulerAnglesZYX(new Vector3f());
        bone.updateRotation(euler.x, euler.y, euler.z);
        bone.updatePosition(0, 0, 0);
        Vector3f d = want.getTranslation(new Vector3f()).sub(local(bone, false).getTranslation(new Vector3f()));
        bone.updatePosition(-d.x * 16, d.y * 16, d.z * 16);
    }

    // ------------------------------------------------------------------------------------------------------------
    // keeping the weapon in the hand
    // ------------------------------------------------------------------------------------------------------------

    /** Bone names that mark where the weapon is held, best first. */
    private static final String[] GRIP_NAMES = {"grip", "handle", "haft", "shaft"};
    private final Map<String, String> gripBones = new HashMap<>();

    /**
     * The artist's animations were made for the weapon on its own: besides moving its parts, many of them carry the
     * whole weapon about - Aetherlance's thrusts slide it two blocks sideways, Eclipse Reaper's and Soulreaper's casts
     * hurl it round in a loop, the swings turn it through 100 degrees. In the hand that tore the weapon out of the
     * wielder's grip and through their body, on top of the player's own swing and cast poses. So the motion of the
     * grip bone is measured every frame and the whole model is moved back by its inverse: the grip stays where the
     * hand holds it, at rest, while every part keeps its animated motion relative to it (rings spinning, petals
     * opening, chain links paying out). The weapon as a whole moves only with the arm.
     */
    private void anchorGrip(FantasyWeaponItem item, String anim, @org.jetbrains.annotations.Nullable com.fantasyweapons.weapon.RigidAnimationController<?> controller) {
        String name = gripBones.computeIfAbsent(item.definition().geoName(), k -> findGrip());
        if (name.isEmpty()) {
            if (rigidStats != null) rigidStats.merge(item.definition().geoName() + " ~nogrip", 1f, Float::sum);
            return;
        }
        GeoBone grip = getBone(name).orElse(null);
        if (grip == null || grip.getParent() == null || grip.getParent().getParent() != null) return;
        GeoBone root = grip.getParent();
        Matrix4f now = local(grip, false);
        Matrix4f rest = local(grip, true);
        if (now.equals(rest, 1e-5f)) return;
        // root * grip(now) must equal root(rest) * grip(rest)
        setLocal(root, local(root, true).mul(rest).mul(now.invert()));
        weldToGrip(item, anim, root, grip, controller);
    }

    /**
     * The artist's models are built of separate pieces hanging straight off the root - the haft, the head, the blade
     * - and a piece belonging to the weapon's body is animated with exactly the same rotation as the grip and a
     * position that carries it round with it. GeckoLib moves positions in a straight line from one keyframe to the
     * next while the piece turns, though, so on a big, fast turn (every swing and cast) the head cuts the corner, off
     * the arc it should follow, and snaps back onto it at the next keyframe: with the grip held still in the hand, the
     * top of the weapon shook on every hit. So every piece turning exactly as the grip does is placed by where it sits
     * relative to the grip at the two keyframes either side, blended in the grip's own frame: exactly the artist's
     * pose at each keyframe, and in between it travels with the grip instead of cutting across. Pieces that also move
     * on their own (chain links paying out, orbiting souls) keep that motion; pieces that turn differently (spinning
     * rings, moons) are left to GeckoLib.
     */
    private void weldToGrip(FantasyWeaponItem item, String anim, GeoBone root, GeoBone grip,
                            @org.jetbrains.annotations.Nullable com.fantasyweapons.weapon.RigidAnimationController<?> controller) {
        if (controller == null) return;
        double[] gs = controller.segments.get(grip.getName());
        if (gs == null || Double.isNaN(gs[0]) || !sameTiming(gs)) {
            if (rigidStats != null) rigidStats.merge(item.definition().geoName() + " ~skip-grip " + anim + (gs == null ? " none" : Double.isNaN(gs[0]) ? " norot" : " timing"), 1f, Float::sum);
            return;
        }
        double f = gs[13] <= 0 ? 1 : Math.min(1, Math.max(0, gs[12] / gs[13]));
        Matrix4f g0 = localAt(grip, gs, false), g1 = localAt(grip, gs, true);
        if (g0.equals(g1, 1e-6f)) return;
        Matrix4f g0inv = new Matrix4f(g0).invert(), g1inv = new Matrix4f(g1).invert();
        Matrix4f gNow = local(grip, false);
        for (GeoBone b : root.getChildBones()) {
            if (b == grip) continue;
            double[] bs = controller.segments.get(b.getName());
            if (bs == null || Double.isNaN(bs[0])) continue;
            boolean together = bs[12] == gs[12] && bs[13] == gs[13];
            for (int i = 0; i < 6 && together; i++) together = Math.abs(bs[i] - gs[i]) < 1e-4;
            if (!together) continue;
            if (!sameTiming(bs)) {
                if (rigidStats != null) rigidStats.merge(item.definition().geoName() + " ~skip-bone-timing " + anim + " " + b.getName(), 1f, Float::sum);
                continue;
            }
            Matrix4f rel = blend(new Matrix4f(g0inv).mul(localAt(b, bs, false)), new Matrix4f(g1inv).mul(localAt(b, bs, true)), (float) f);
            Matrix4f want = new Matrix4f(gNow).mul(rel);
            if (rigidStats != null) {
                Vector3f piv = new Vector3f(b.getPivotX() / 16f, b.getPivotY() / 16f, b.getPivotZ() / 16f);
                float err = want.transformPosition(new Vector3f(piv)).distance(local(b, false).transformPosition(new Vector3f(piv)));
                rigidStats.merge(item.definition().geoName() + " " + anim + " " + b.getName(), err, Math::max);
            }
            setLocal(b, want);
        }
    }

    /** Whether a bone's position keyframes (if any) run on the same timing as its rotation keyframes. */
    private static boolean sameTiming(double[] seg) {
        return Double.isNaN(seg[14]) || (seg[14] == seg[12] && seg[15] == seg[13]);
    }

    /** The bone's transform relative to its parent at the start or end of its current keyframe segment. */
    private static Matrix4f localAt(GeoBone bone, double[] seg, boolean end) {
        float px = bone.getPosX(), py = bone.getPosY(), pz = bone.getPosZ(), rx = bone.getRotX(), ry = bone.getRotY(), rz = bone.getRotZ();
        BoneSnapshot init = bone.getInitialSnapshot();
        int r = end ? 3 : 0, p = end ? 9 : 6;
        bone.updateRotation((float) seg[r] + init.getRotX(), (float) seg[r + 1] + init.getRotY(), (float) seg[r + 2] + init.getRotZ());
        if (!Double.isNaN(seg[p])) bone.updatePosition((float) seg[p], (float) seg[p + 1], (float) seg[p + 2]);
        Matrix4f m = local(bone, false);
        bone.updatePosition(px, py, pz);
        bone.updateRotation(rx, ry, rz);
        return m;
    }

    /** DEVELOPMENT ONLY: the largest weld correction per weapon / animation / piece, in blocks (null: not recording). */
    public static Map<String, Float> rigidStats;

    /** A rigid transform part way from {@code a} to {@code b}. */
    private static Matrix4f blend(Matrix4f a, Matrix4f b, float t) {
        org.joml.Quaternionf q = a.getNormalizedRotation(new org.joml.Quaternionf()).slerp(b.getNormalizedRotation(new org.joml.Quaternionf()), t);
        Vector3f p = a.getTranslation(new Vector3f()).lerp(b.getTranslation(new Vector3f()), t);
        return new Matrix4f().translation(p).rotate(q);
    }

    /**
     * Loose pieces of the artist's ability animations - Starforge's meteor fragments and meteor, Aetherlance's bolt
     * and blade shards, Voidfang's fragments and phase echo, the souls of the reapers, the Monolith's rock shards -
     * fly a block or more away from the weapon while it casts: they were made for the weapon on its own, as the
     * projectiles leaving it. In the hand they floated about the wielder like debris, so while a cast, charge, impact
     * or recovery animation plays they shrink away, and they grow back in idle.
     */
    private static final String[] STRAYS = {"meteor_fragment_", "meteor_projectile", "projectile", "blade_fragment_", "fragment_", "phase_echo", "rock_fragment_",
            "soul_0", "soul_1", "soul_2", "soul_3", "soul_4", "soul_5", "spectral_link_", "chain_hook"};
    private final Map<String, Float> strayScale = new HashMap<>();
    private long strayNanos;

    private void fadeStrays(FantasyWeaponItem item, software.bernie.geckolib.animation.AnimatableManager<?> manager) {
        var controller = manager.getAnimationControllers().get(FantasyWeaponItem.CONTROLLER);
        var current = controller == null ? null : controller.getCurrentAnimation();
        String name = current == null ? "" : current.animation().name();
        boolean casting = !name.endsWith(".idle") && !name.endsWith("_idle") && !name.endsWith(".attack") && !name.endsWith(".heavy_attack")
                && !name.endsWith(".whip") && !name.isEmpty();
        long now = System.nanoTime();
        float step = strayNanos == 0 ? 1 : Math.min(1, (now - strayNanos) / 1e9f * 8f);
        strayNanos = now;
        String geo = item.definition().geoName();
        for (GeoBone b : getAnimationProcessor().getRegisteredBones()) {
            String n = b.getName();
            boolean stray = false;
            for (String k : STRAYS) {
                if (n.startsWith(k) || n.equals(k)) {
                    stray = true;
                    break;
                }
            }
            // the reapers' and Gravebite's souls, the lantern's spark excepted, are the only "soul_" strays
            if (!stray || n.startsWith("soul_crystal")) continue;
            String key = geo + "/" + n;
            float s = strayScale.getOrDefault(key, 1f);
            s += ((casting ? 0f : 1f) - s) * step;
            strayScale.put(key, s);
            if (s < 0.999f) b.updateScale(b.getScaleX() * s, b.getScaleY() * s, b.getScaleZ() * s);
            if (s < 0.02f) b.setHidden(true);
            else if (b.isHidden() && !n.startsWith("spectral_chain")) b.setHidden(false);
        }
    }

    /** The first bone named like a grip (see {@link #GRIP_NAMES}) that hangs straight off the root; "" if none. */
    private String findGrip() {
        for (String key : GRIP_NAMES) {
            for (GeoBone b : getAnimationProcessor().getRegisteredBones()) {
                String n = b.getName();
                if (n.contains(key) && !n.contains("pommel") && b.getParent() != null && b.getParent().getParent() == null) return n;
            }
        }
        return "";
    }

    /** The bone's transform relative to its parent (as GeckoLib renders it, scale aside), now or at rest. */
    private static Matrix4f local(GeoBone bone, boolean atRest) {
        float px = bone.getPosX(), py = bone.getPosY(), pz = bone.getPosZ(), rx = bone.getRotX(), ry = bone.getRotY(), rz = bone.getRotZ();
        if (atRest) {
            BoneSnapshot init = bone.getInitialSnapshot();
            bone.updatePosition(init.getOffsetX(), init.getOffsetY(), init.getOffsetZ());
            bone.updateRotation(init.getRotX(), init.getRotY(), init.getRotZ());
        }
        PoseStack ps = new PoseStack();
        RenderUtil.translateMatrixToBone(ps, bone);
        RenderUtil.translateToPivotPoint(ps, bone);
        RenderUtil.rotateMatrixAroundBone(ps, bone);
        RenderUtil.translateAwayFromPivotPoint(ps, bone);
        if (atRest) {
            bone.updatePosition(px, py, pz);
            bone.updateRotation(rx, ry, rz);
        }
        return new Matrix4f(ps.last().pose());
    }

}
