package com.fantasyweapons.client.render;

import com.fantasyweapons.FantasyWeapons;
import com.fantasyweapons.weapon.FantasyWeaponItem;
import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix3f;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import software.bernie.geckolib.animation.AnimationState;
import software.bernie.geckolib.animation.state.BoneSnapshot;
import software.bernie.geckolib.cache.object.GeoBone;
import software.bernie.geckolib.model.GeoModel;
import software.bernie.geckolib.util.RenderUtil;

import java.util.HashMap;
import java.util.Map;

/**
 * Points GeckoLib at the artist-supplied files. Supplementary animations (generated by tools/gen_extra_animations.py,
 * e.g. Infernochain's {@code chain_idle}) live in {@code <weapon>_extra.animation.json} and are found via the fallback
 * list, so the original animation files are never modified.
 */
public class WeaponGeoModel extends GeoModel<FantasyWeaponItem> {
    @Override
    public ResourceLocation getModelResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("geo/item/" + item.definition().geoName() + ".geo.json");
    }

    @Override
    public ResourceLocation getTextureResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("textures/item/" + item.definition().geoName() + ".png");
    }

    @Override
    public ResourceLocation getAnimationResource(FantasyWeaponItem item) {
        return FantasyWeapons.id("animations/item/" + item.definition().geoName() + ".animation.json");
    }

    @Override
    public ResourceLocation[] getAnimationResourceFallbacks(FantasyWeaponItem item) {
        return new ResourceLocation[]{FantasyWeapons.id("animations/item/" + item.definition().geoName() + "_extra.animation.json")};
    }

    /** DEVELOPMENT ONLY: logs the rendered rotation of this bone every frame (to check blends don't unwind). */
    public static String debugBone;

    /**
     * Several of the artist's animations end with parts turned through whole revolutions (Stormbreaker's Tempest
     * Spin finishes its head at 720 degrees), or in a second form of the rest orientation such as (-180, 0, 180).
     * GeckoLib blends into the next animation from the raw angles, so the part would visibly unwind, or swing out
     * sideways about its own pivot. After every frame the remembered angles are restated in the equivalent Euler
     * angles nearest the rest pose, so every blend takes the short way round (see {@link
     * com.fantasyweapons.weapon.RigidAnimationController}, which does the same towards the next animation's start).
     */
    @Override
    public void setCustomAnimations(FantasyWeaponItem animatable, long instanceId, AnimationState<FantasyWeaponItem> state) {
        super.setCustomAnimations(animatable, instanceId, state);
        if (debugBone != null) {
            getBone(debugBone).ifPresent(b -> FantasyWeapons.LOGGER.warn("[bone] {} {} {} {}", debugBone, Math.toDegrees(b.getRotX()), Math.toDegrees(b.getRotY()),
                    Math.toDegrees(b.getRotZ())));
        }
        var manager = animatable.getAnimatableInstanceCache().getManagerForId(instanceId);
        if (manager == null) return;
        for (BoneSnapshot snap : manager.getBoneSnapshotCollection().values()) {
            BoneSnapshot rest = snap.getBone().getInitialSnapshot();
            // the same orientation in the Euler angles nearest the rest pose: blends back to rest (or into a bone
            // the next animation leaves alone) then take the short way round about one axis
            double[] e = com.fantasyweapons.weapon.RigidAnimationController.closestEuler(snap.getRotX() - rest.getRotX(), snap.getRotY() - rest.getRotY(),
                    snap.getRotZ() - rest.getRotZ(), 0, 0, 0);
            float x = (float) e[0] + rest.getRotX(), y = (float) e[1] + rest.getRotY(), z = (float) e[2] + rest.getRotZ();
            if (x != snap.getRotX() || y != snap.getRotY() || z != snap.getRotZ()) snap.updateRotation(x, y, z);
        }
        anchorGrip(animatable);
    }

    // ------------------------------------------------------------------------------------------------------------
    // keeping the weapon in the hand
    // ------------------------------------------------------------------------------------------------------------

    /** Bone names that mark where the weapon is held, best first. */
    private static final String[] GRIP_NAMES = {"grip", "handle", "haft", "shaft"};
    private final Map<String, String> gripBones = new HashMap<>();

    /**
     * The artist's animations were made for the weapon on its own: besides moving its parts, many of them carry the
     * whole weapon about - Aetherlance's thrusts slide it two blocks sideways, Eclipse Reaper's and Soulreaper's casts
     * hurl it round in a loop, the swings turn it through 100 degrees. In the hand that tore the weapon out of the
     * wielder's grip and through their body, on top of the player's own swing and cast poses. So the motion of the
     * grip bone is measured every frame and the whole model is moved back by its inverse: the grip stays where the
     * hand holds it, at rest, while every part keeps its animated motion relative to it (rings spinning, petals
     * opening, chain links paying out). The weapon as a whole moves only with the arm.
     */
    private void anchorGrip(FantasyWeaponItem item) {
        String name = gripBones.computeIfAbsent(item.definition().geoName(), k -> findGrip());
        if (name.isEmpty()) return;
        GeoBone grip = getBone(name).orElse(null);
        if (grip == null || grip.getParent() == null || grip.getParent().getParent() != null) return;
        GeoBone root = grip.getParent();
        Matrix4f now = local(grip, false);
        Matrix4f rest = local(grip, true);
        if (now.equals(rest, 1e-5f)) return;
        // root * grip(now) must equal root(rest) * grip(rest)
        Matrix4f want = local(root, true).mul(rest).mul(now.invert());
        Vector3f euler = want.get3x3(new Matrix3f()).getEulerAnglesZYX(new Vector3f());
        root.updateRotation(euler.x, euler.y, euler.z);
        root.updatePosition(0, 0, 0);
        Vector3f d = want.getTranslation(new Vector3f()).sub(local(root, false).getTranslation(new Vector3f()));
        root.updatePosition(-d.x * 16, d.y * 16, d.z * 16);
    }

    /** The first bone named like a grip (see {@link #GRIP_NAMES}) that hangs straight off the root; "" if none. */
    private String findGrip() {
        for (String key : GRIP_NAMES) {
            for (GeoBone b : getAnimationProcessor().getRegisteredBones()) {
                String n = b.getName();
                if (n.contains(key) && !n.contains("pommel") && b.getParent() != null && b.getParent().getParent() == null) return n;
            }
        }
        return "";
    }

    /** The bone's transform relative to its parent (as GeckoLib renders it, scale aside), now or at rest. */
    private static Matrix4f local(GeoBone bone, boolean atRest) {
        float px = bone.getPosX(), py = bone.getPosY(), pz = bone.getPosZ(), rx = bone.getRotX(), ry = bone.getRotY(), rz = bone.getRotZ();
        if (atRest) {
            BoneSnapshot init = bone.getInitialSnapshot();
            bone.updatePosition(init.getOffsetX(), init.getOffsetY(), init.getOffsetZ());
            bone.updateRotation(init.getRotX(), init.getRotY(), init.getRotZ());
        }
        PoseStack ps = new PoseStack();
        RenderUtil.translateMatrixToBone(ps, bone);
        RenderUtil.translateToPivotPoint(ps, bone);
        RenderUtil.rotateMatrixAroundBone(ps, bone);
        RenderUtil.translateAwayFromPivotPoint(ps, bone);
        if (atRest) {
            bone.updatePosition(px, py, pz);
            bone.updateRotation(rx, ry, rz);
        }
        return new Matrix4f(ps.last().pose());
    }

}
