package com.fantasyweapons.client.vfx;

import com.fantasyweapons.FantasyWeapons;
import net.minecraft.resources.ResourceLocation;

/** Custom VFX textures generated by tools/gen_textures.py (white shapes, tinted at runtime). */
public final class VfxTextures {
    private VfxTextures() {
    }

    private static ResourceLocation t(String name) {
        return FantasyWeapons.id("textures/vfx/" + name + ".png");
    }

    public static final ResourceLocation GLOW = t("glow");
    public static final ResourceLocation FLASH = t("flash");
    public static final ResourceLocation RING = t("ring");
    public static final ResourceLocation SHOCKWAVE = t("shockwave");
    public static final ResourceLocation NOISE = t("noise");
    public static final ResourceLocation SLASH = t("slash");
    public static final ResourceLocation STREAK = t("streak");
    public static final ResourceLocation LIGHTNING = t("lightning");
    public static final ResourceLocation SPARK = t("spark");
    public static final ResourceLocation SHARD = t("shard");
    public static final ResourceLocation SWIRL = t("swirl");
    public static final ResourceLocation RIFT_EDGE = t("rift_edge");
    public static final ResourceLocation RUNE_CIRCLE = t("rune_circle");
    public static final ResourceLocation CRACK = t("crack");
    public static final ResourceLocation FLAME = t("flame");
    public static final ResourceLocation MIST = t("mist");
    public static final ResourceLocation HEX = t("hex");
    public static final ResourceLocation SOUL = t("soul");
    public static final ResourceLocation PETAL = t("petal");
    public static final ResourceLocation LEAF = t("leaf");
    public static final ResourceLocation STAR = t("star");
    public static final ResourceLocation WHITE = t("white");
    public static final ResourceLocation DISC = t("disc");
    public static final ResourceLocation ICE = t("ice");
    public static final ResourceLocation ROCK = t("rock");
    public static final ResourceLocation BARK = t("bark");
    public static final ResourceLocation FROST = t("frost");
}
